---
- name: Install composer
  become: true
  become_method: sudo
  become_user: root
  apt:
    name: composer
    state: latest

- name: Install ytdl
  become: true
  become_method: sudo
  become_user: root
  apt:
    name: youtube-dl
    state: latest

- name: Install msyql-client
  become: true
  become_method: sudo
  become_user: root
  apt:
    name: default-mysql-client
    state: latest
