# Ansible launch multi-instance
- name: Launch a compute instance
  hosts: localhost
  tasks:
- name: Launch a VM
  os_server:
    image: Ubuntu 14.04 LTS x64
    name: "{{ item.name }}"
  key_name: my_keypair_dd2d
  availability_zone: nova
  flavor: "{{ item.flavor}}"
  state: present
  network: floatingIPv4
  register: my_vm
  with_items:
    - { name: vm1, flavor: 22 }
    - { name: vm2, flavor: 22 }
    - { name: vm3, flavor: 23 }
- name: Add VM to inventory
  add_host:
    name: "{{ item.server.name }}"
    groups: openstack_vms
    ansible_host: "{{ item.server.public_v4 }}"
    with_items: "{{ my_vm.results }}"
- name: Wait to be sure ssh is available
  pause:
  seconds: 30
