---
- hosts: all
  tasks:
    - name: Ping All Servers
      action: ping
    - debug: msg="Hello"

    - name: Execute Shell Commands
      shell: uname
      register: uname_result
    - debug: msg="{{ uname_result.stdout }}"

    - name: Check Hosts
      shell: cat /etc/hosts
      register: cat_result
    - debug: msg="{{ cat_result.stdout }}"